#!/bin/bash

function get_args() {
    if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] ; then
    echo "Usage: $0 <HOST> <USERNAME> <PASSWORD> <OUTPATH>"
    echo
    echo "Pull libraries from remote camera over FTP."
    exit 1
    fi
}

function fetch_libs() { # params : ftp folder path, libs strings array
    local -n local_arr=$1
    for LIB in "${local_arr[@]}"
    do
        /usr/bin/curl -u "$USERNAME:$PASSWORD" "ftp://${HOST}$2/$LIB" --output "./lib/$LIB" 
    done
}


HOST="$1" USERNAME="$2" PASSWORD="$3"
LIB_PATH="$3"

mnt_libs=("libdevice_kit.so.0.0.1" "libmortox.so.0.0.0" "libboardav.so.1.0.0" \
                    "libmortox_share.so.0.0.0" "libmiio_util.so.0.0.1" "libmortoxev.so.0.0.0" \
                    "libmi_isp.so" "libMTE_LINUX.so")


get_args
mkdir -p "$(pwd)/lib"
fetch_libs mnt_libs "/mnt/data/lib"
