name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        releases: [ 'debug', 'release' ]
        rust-toolchain: [ 'stable' ]
        rust-target: [ 'x86_64-unknown-linux-gnu', 'armv7-unknown-linux-gnueabihf' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup rust '${{ matrix.rust-toolchain }}-${{ matrix.rust-target }}' environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-toolchain }}
          target: ${{ matrix.rust-target }}
          components: rustfmt, clippy

      - run: make ${{ matrix.releases }}
